### ISSUE TITLE
Inward remittance and type of bank account

### ISSUE THREAD

**Issue by mzfr** [rootxharsh/beautify-hdfc-statement#1]
Hey,

I have one doubt with HDFC Bank account.

With some providers (yeswehack, google) when you receive payment hdfc generates inward remittance and they ask you purpose code for it.

But recently they(bank executives) told me that these kind of payments cannot be accepted in savings account and requires a current account and will be considered business payment.

So my question is did you ever had any such issue? If yes did you had to open a current account?

And I apologise in advance if this sort of question looks weird but from past few days I'm tried to contact indian bounty hunters and haven't got a solid reply from any one

Thanks

**Comment by mrd17** [comment]
Thanks @rootxharsh for making this.

I would really appreciate if you or any Indian Bughunter can give some suggestion on this.
It will help me @mzfr and other Indian Bug Hunters who are facing the same situation.
Regards

**Comment by rootxharsh** [comment]
@mzfr @mrd17 - I've faced that as well, in my case, I just went to the branch and met the branch manager, made them understand the whole scenario. They never raised it again.

**Comment by mzfr** [comment]
@rootxharsh so you never had to open any current account or anything like that?
